b2c:
  ourhealth:
    tenantName: ourhealthdev
    clientId: 206a23da-f303-4a9b-ad86-f51d1be51777
    policyName: B2C_1A_DDP_participant_signup_signin_ourhealth-dev
    changePasswordPolicyName: B2C_1A_DDP_participant_change_password_ourhealth-dev
  hearthive:
    tenantName: hearthivedev
    clientId: 8c778931-b7f6-4503-b30e-e975ab8ea615
    policyName: B2C_1A_ddp_participant_signup_signin_hearthive-dev
    changePasswordPolicyName: B2C_1A_ddp_participant_change_password_hearthive-dev
  demo:
    tenantName: juniperdemodev
    clientId: 37d95cc4-7c71-465e-9fc2-66be9a54c202
    policyName: B2C_1A_ddp_participant_signup_signin_demo-dev
    changePasswordPolicyName: B2C_1A_ddp_participant_change_password_demo-dev
