gcpProject: broad-juniper-dev
gcpRegion: us-central1
adminUrl: juniper-cmi.dev
replicas: 1
# "portals" adds certificates for each portal - both for the juniper-cmi.dev subdomains and the custom domain
portals:
  - name: demo
    customDomain: juniperdemostudy.dev
  - name: hearthive
  - name: ourhealth
  - name: cmi
  - name: rgp
  - name: atcp
b2c:
  admin:
    clientId: 705c09dc-5cca-43d3-ae06-07de78bad29a
    tenantName: ddpdevb2c
    policyName: B2C_1A_ddp_admin_signup_signin_dev
  portals:
    atcp:
      changePasswordPolicyName: does-not-exist
      clientId: does-not-exist
      policyName: does-not-exist
      tenantName: does-not-exist
    cmi:
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_cmi-dev
      clientId: 0cdfdafd-75fb-4e36-b6a2-c00e79c86bb0
      policyName: B2C_1A_ddp_participant_signup_signin_cmi-dev
      tenantName: junipercmidemo
    demo:
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_demo-dev
      clientId: 37d95cc4-7c71-465e-9fc2-66be9a54c202
      policyName: B2C_1A_ddp_participant_signup_signin_demo-dev
      tenantName: juniperdemodev
    gvasc:
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_gvasc-dev
      clientId: 441d57d2-5f17-473b-8b19-a2ed523c09bf
      policyName: B2C_1A_ddp_participant_signup_signin_gvasc-dev
      tenantName: gvascdev
    hearthive:
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_hearthive-dev
      clientId: 8c778931-b7f6-4503-b30e-e975ab8ea615
      policyName: B2C_1A_ddp_participant_signup_signin_hearthive-dev
      tenantName: hearthivedev
    ourhealth:
      changePasswordPolicyName: B2C_1A_DDP_participant_change_password_ourhealth-dev
      clientId: 206a23da-f303-4a9b-ad86-f51d1be51777
      policyName: B2C_1A_DDP_participant_signup_signin_ourhealth-dev
      tenantName: ourhealthdev
    rgp:
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_rgp-dev
      clientId: 42445bb9-7ab2-48e9-b7a7-c5f84258e87b
      policyName: B2C_1A_ddp_participant_signup_signin_rgp-dev
      tenantName: juniperrgpdemo
    template:
      changePasswordPolicyName: does-not-exist
      clientId: does-not-exist
      policyName: does-not-exist
      tenantName: does-not-exist
