adminUrl: ""
replicas: 1
portals:
  - name: ""
    customDomain: ""
gcpProject: ""
gcpRegion: ""
appVersion: 1.4.0
b2c:
  admin:
    clientId: ""
    policyName: ""
    tenantName: ""
  portals:
    portalName:
      tenantName: ""
      policyName: ""
      clientId: ""
      changePasswordPolicyName: ""
