apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: juniper-app-ksa
      containers:
        - name: cloud-sql-proxy
          # It is recommended to use the latest version of the Cloud SQL Auth Proxy
          # Make sure to update on a regular schedule!
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
          args:
            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            - "--private-ip"

            # Enable structured logging with LogEntry format:
            - "--structured-logs"

            # Replace DB_PORT with the port the proxy should listen on
            - "--port=5432"
            - "{{ .Values.gcpProject }}:{{ .Values.gcpRegion }}:d2p"

          securityContext:
            # The default Cloud SQL Auth Proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          # You should use resource requests/limits as a best practice to prevent
          # pods from consuming too many resources and affecting the execution of
          # other pods. You should adjust the following values based on what your
          # application needs. For details, see
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            requests:
              # The proxy's memory use scales linearly with the number of active
              # connections. Fewer open connections will use less memory. Adjust
              # this value based on your application's requirements.
              memory: "2Gi"
              # The proxy's CPU use scales linearly with the amount of IO between
              # the database and the application. Adjust this value based on your
              # application's requirements.
              cpu: "1"

        - name: admin
          imagePullPolicy: Always
          image: "us-central1-docker.pkg.dev/broad-juniper-eng-infra/juniper/juniper-admin:{{.Values.appVersion}}"
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /version
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: gcp
            - name: DB_NAME_SECRET_ID
              value: "d2p-db-name"
            - name: DB_PASSWORD_SECRET_ID
              value: "d2p-db-password"
            - name: DB_USER_SECRET_ID
              value: "d2p-db-user"
            - name: GCP_PROJECT_ID
              value: {{ .Values.gcpProject }}
            - name: DATABASE_NAME
              value: "d2p"
            - name: DEPLOYMENT_ZONE
              value: dev
            - name: ADMIN_API_HOSTNAME
              value: {{ .Values.adminUrl }}
            - name: ADMIN_UI_HOSTNAME
              value: {{ .Values.adminUrl }}
            - name: PARTICIPANT_API_HOSTNAME
              value: {{ .Values.adminUrl }}
            - name: PARTICIPANT_UI_HOSTNAME
              value: {{ .Values.adminUrl }}
            - name: B2C_CLIENT_ID
              value: {{ .Values.b2c.admin.clientId }}
            - name: B2C_POLICY_NAME
              value: {{ .Values.b2c.admin.policyName }}
            - name: B2C_TENANT_NAME
              value: {{ .Values.b2c.admin.tenantName }}
            - name: TDR_ADDRESS
              value: https://jade.datarepo-dev.broadinstitute.org
            - name: TDR_EXPORT_ENABLED
              value: 'true'
            - name: TDR_EXPORT_STORAGE_ACCOUNT_NAME
              value: juniperdevtdr
            - name: TDR_EXPORT_STORAGE_CONTAINER_NAME
              value: juniper-dataset-ingest
            - name: ADDRESS_VALIDATION_SERVICE_CLASS
              value: SmartyUSAddressValidationService
            - name: SMARTY_AUTH_ID_SECRET_ID
              value: smarty-auth-id
            - name: SMARTY_AUTH_TOKEN_SECRET_ID
              value: smarty-auth-token
            - name: SENDGRID_API_KEY_SECRET_ID
              value: sendgrid-api-key
            - name: DSM_JWT_ISSUER
              value: admin-d2p.ddp-dev.envs.broadinstitute.org
            - name: DSM_JWT_SIGNING_SECRET_SECRET_ID
              value: dsm-secret
            - name: DSM_ADDRESS
              value: https://dsm-dev.datadonationplatform.org/dsm
            - name: TDR_SA_CREDS_SECRET_ID
              value: tdr-sa-creds
            - name: TDR_EXPORT_STORAGE_ACCOUNT_KEY_SECRET_ID
              value: tdr-storage-account-key
          resources:
            requests:
              # The proxy's memory use scales linearly with the number of active
              # connections. Fewer open connections will use less memory. Adjust
              # this value based on your application's requirements.
              memory: "2Gi"
              # The proxy's CPU use scales linearly with the amount of IO between
              # the database and the application. Adjust this value based on your
              # application's requirements.
              cpu: "500m"
          volumeMounts:
            - mountPath: /etc/app/portalB2CConfig.yaml
              name: portal-b2c-configmap-mount
              readOnly: true
              subPath: portalB2CConfig.yaml
        - image: us.gcr.io/broad-dsp-gcr-public/httpd-terra-proxy:v0.1.18
          imagePullPolicy: IfNotPresent
          name: oidc-proxy
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: REMOTE_USER_CLAIM
              value: sub
            - name: B2C_APPLICATION_ID
              value: {{ .Values.b2c.admin.clientId }}
          volumeMounts:
            - mountPath: /etc/httpd/conf.d/site.conf
              name: d2p-site-configmap-mount
              readOnly: true
              subPath: site.conf
            - mountPath: /etc/httpd/conf.d/oauth2.conf
              name: d2p-oauth2-configmap-mount
              readOnly: true
              subPath: oauth2.conf
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /version
              port: 80
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 1110
            httpGet:
              path: /version
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - configMap:
            defaultMode: 420
            name: d2p-oauth2-configmap
          name: d2p-oauth2-configmap-mount
        - configMap:
            defaultMode: 420
            name: d2p-site-configmap
          name: d2p-site-configmap-mount
        - configMap:
            defaultMode: 420
            name: portal-b2c-configmap
          name: portal-b2c-configmap-mount
