apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: juniper-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  sslPolicy: juniper-ssl-policy
